/**
 * Smart deployment config generation.
 * Detects project type and injects whatever config + code transforms
 * are needed for the app to actually run on the target platform.
 */

export interface FileEntry {
  path: string;
  content: string;
}

export type ProjectType =
  | "static"       // index.html, plain HTML/CSS/JS — works everywhere
  | "node-server"  // Express / http.createServer — needs serverless adapter
  | "node-script"  // Node.js that just runs and exits (not a web server)
  | "python-server"// Flask/FastAPI
  | "python-script"// Python script that runs and exits
  | "unknown";

export function detectType(files: FileEntry[]): ProjectType {
  const paths = files.map((f) => f.path);
  const allContent = files.map((f) => f.content).join("\n");

  const hasHtml  = paths.some((p) => p.endsWith(".html"));
  const hasJs    = paths.some((p) => p.endsWith(".js") || p.endsWith(".ts"));
  const hasPy    = paths.some((p) => p.endsWith(".py"));

  const isHttpServer = /app\.listen\s*\(|http\.createServer\s*\(|https\.createServer\s*\(/.test(allContent);
  const isFlask      = /Flask\s*\(|@app\.route|from flask/.test(allContent);
  const isFastApi    = /FastAPI\s*\(|@app\.(get|post|put|delete)\s*\(/.test(allContent);

  if (hasHtml) return "static";
  if (hasPy && (isFlask || isFastApi)) return "python-server";
  if (hasPy) return "python-script";
  if (hasJs && isHttpServer) return "node-server";
  if (hasJs) return "node-script";
  return "unknown";
}

/**
 * Returns the full set of files to deploy to Vercel.
 * Merges injected config/transforms over the original file list.
 */
export function prepareVercelFiles(files: FileEntry[]): {
  files: FileEntry[];
  type: ProjectType;
  warning?: string;
} {
  const type = detectType(files);
  const map = new Map(files.map((f) => [f.path, f.content]));

  if (type === "node-server") {
    // Find entry point
    const entry =
      files.find((f) => ["index.js", "main.js", "server.js", "app.js"].includes(f.path)) ??
      files.find((f) => f.path.endsWith(".js") && /app\.listen|createServer/.test(f.content));

    if (entry) {
      // Transform: replace app.listen(...) with module.exports = app
      // so Vercel can import it as a serverless function
      const transformed = entry.content
        .replace(/app\.listen\s*\([^;)]*(?:\([^)]*\)[^;)]*)*\)\s*(?:,\s*(?:function\s*)?\([^)]*\)\s*\{[^}]*\})?;?/g, "module.exports = app;")
        .replace(/server\.listen\s*\([^;)]*\)\s*;?/g, "module.exports = app;");

      map.set(entry.path, transformed);

      // vercel.json — routes all traffic to the entry point
      map.set("vercel.json", JSON.stringify({
        version: 2,
        builds: [{ src: entry.path, use: "@vercel/node" }],
        routes: [{ src: "/(.*)", dest: `/${entry.path}` }],
      }, null, 2));
    }
  } else if (type === "python-server") {
    const entry =
      files.find((f) => ["app.py", "main.py", "server.py", "api.py"].includes(f.path)) ??
      files.find((f) => f.path.endsWith(".py") && /Flask|FastAPI/.test(f.content));

    if (entry) {
      map.set("vercel.json", JSON.stringify({
        version: 2,
        builds: [{ src: entry.path, use: "@vercel/python" }],
        routes: [{ src: "/(.*)", dest: `/${entry.path}` }],
      }, null, 2));
    }
  } else if (type === "node-script" || type === "python-script") {
    return {
      files: toArray(map),
      type,
      warning:
        "This project runs a script, not a web server. Deploy will upload the files but there's no HTTP endpoint to visit. Ask the agent to wrap it in an Express server first.",
    };
  }

  return { files: toArray(map), type };
}

/**
 * Returns the full set of files to deploy to Netlify.
 */
export function prepareNetlifyFiles(files: FileEntry[]): {
  files: FileEntry[];
  type: ProjectType;
  warning?: string;
} {
  const type = detectType(files);
  const map = new Map(files.map((f) => [f.path, f.content]));

  if (type === "static") {
    // Netlify handles static sites natively — just add a toml so it doesn't
    // try to run a build command.
    if (!map.has("netlify.toml")) {
      map.set("netlify.toml", `[build]\n  publish = "."\n`);
    }
  } else if (type === "node-server") {
    const entry =
      files.find((f) => ["index.js", "main.js", "server.js", "app.js"].includes(f.path)) ??
      files.find((f) => f.path.endsWith(".js") && /app\.listen|createServer/.test(f.content));

    if (entry) {
      const entryBase = entry.path.replace(/\.[jt]s$/, "");

      // Netlify function wrapper — import the app and export a serverless handler
      // Uses the built-in netlify adapter (no extra package needed for basic routing)
      const fnContent = `// Auto-generated by Clownin — wraps Express for Netlify Functions
const app = require("../../${entryBase}");
const serverless = require("serverless-http");

// Remove app.listen if it runs on import — patch it here just in case
app.listen = () => {};

exports.handler = serverless(app);
`;
      map.set("netlify/functions/server.js", fnContent);

      // Transform main file: remove app.listen so it doesn't error on import
      const transformed = entry.content.replace(
        /app\.listen\s*\([^;)]*(?:\([^)]*\)[^;)]*)*\)\s*(?:,\s*(?:function\s*)?\([^)]*\)\s*\{[^}]*\})?;?/g,
        "// app.listen removed for serverless deployment"
      );
      map.set(entry.path, transformed);

      // netlify.toml — functions directory + redirect all traffic
      map.set("netlify.toml", `[build]
  command = "npm install --production"
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
`);

      // Inject serverless-http into package.json if it exists
      const pkgJson = map.get("package.json");
      if (pkgJson) {
        try {
          const pkg = JSON.parse(pkgJson);
          pkg.dependencies = pkg.dependencies ?? {};
          pkg.dependencies["serverless-http"] = "^3.2.0";
          map.set("package.json", JSON.stringify(pkg, null, 2));
        } catch {
          // leave as-is if unparseable
        }
      } else {
        // Create minimal package.json
        map.set("package.json", JSON.stringify({
          name: "clownin-app",
          version: "1.0.0",
          dependencies: { "serverless-http": "^3.2.0" },
        }, null, 2));
      }
    }
  } else if (type === "node-script" || type === "python-script") {
    return {
      files: toArray(map),
      type,
      warning:
        "This project runs a script, not a web server. Deploy will upload the files but there's no HTTP endpoint to visit.",
    };
  }

  return { files: toArray(map), type };
}

function toArray(map: Map<string, string>): FileEntry[] {
  return Array.from(map.entries()).map(([path, content]) => ({ path, content }));
}
