// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/Screenshot55.tsx": () => import("../components/mockups/Screenshot55.tsx"),
  "./components/mockups/Screenshot67.tsx": () => import("../components/mockups/Screenshot67.tsx")
};
