/**
 * Manual extension: test a stored provider key without activating it.
 * Not generated by orval — maintained by hand alongside the generated client.
 */
import { useMutation } from "@tanstack/react-query";
import type { UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { customFetch, type ErrorType } from "./custom-fetch";

export interface ProviderTestResult {
  ok: boolean;
  /** Model's reply on success */
  response?: string;
  /** Error message on failure */
  error?: string;
}

export const testProvider = async (
  provider: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<ProviderTestResult> => {
  return customFetch<ProviderTestResult>(`/api/admin/providers/${provider}/test`, {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
  });
};

export const useTestProvider = <TError = ErrorType<{ message: string }>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      ProviderTestResult,
      TError,
      { provider: string },
      TContext
    >;
  },
): UseMutationResult<ProviderTestResult, TError, { provider: string }, TContext> => {
  return useMutation({
    mutationKey: ["testProvider"],
    mutationFn: ({ provider }) => testProvider(provider),
    ...options?.mutation,
  });
};
