/**
 * Manual extension: check whether the active provider's stored key can be decrypted.
 * Not generated by orval — maintained by hand alongside the generated client.
 */
import { useQuery } from "@tanstack/react-query";
import type { UseQueryOptions, UseQueryResult } from "@tanstack/react-query";
import { customFetch, type ErrorType } from "./custom-fetch";

export interface ProviderHealthResult {
  ok: boolean;
  /** The active DB-configured provider (or null) */
  provider: string | null;
  /** The provider actually serving requests right now (or null when unreachable) */
  activeProvider?: string | null;
  /** true when the stored key for the active provider failed to decrypt */
  decryptError?: boolean;
  /** true when falling back to env-var provider (no DB key to decrypt) */
  usingEnvFallback?: boolean;
  /** true when the provider is active but no key has been stored yet */
  noKeyStored?: boolean;
  /** true when there is no usable provider at all — neither a DB key nor an env-var key */
  noProvider?: boolean;
  /** Human-readable error when ok === false */
  error?: string;
}

export const getProviderHealthQueryKey = () => ["/api/admin/provider-health"] as const;

export const providerHealth = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<ProviderHealthResult> => {
  return customFetch<ProviderHealthResult>("/api/admin/provider-health", {
    ...options,
    method: "GET",
  });
};

export const useProviderHealth = <
  TData = ProviderHealthResult,
  TError = ErrorType<{ message: string }>,
>(
  options?: {
    query?: UseQueryOptions<ProviderHealthResult, TError, TData>;
  },
): UseQueryResult<TData, TError> => {
  const queryKey = getProviderHealthQueryKey();
  return useQuery({
    queryKey,
    queryFn: () => providerHealth(),
    // Refresh every 30 s so stale-key issues surface automatically
    refetchInterval: 30_000,
    ...options?.query,
  });
};
